// Emits the typed locale exports from src/locales/*.json, which Weblate owns.
// Generated rather than committed so a JSON-only Weblate PR cannot leave it stale.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const localesDir = resolve(root, 'src/locales');
const read = (code) => JSON.parse(readFileSync(resolve(localesDir, `${code}.json`), 'utf8'));

const codes = readdirSync(localesDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
    .sort();

if (!codes.includes('en')) throw new Error('src/locales/en.json is missing');

// Catches Weblate switching to pt_BR.json style, which would ship a second copy of a locale
const malformed = codes.filter((code) => !/^[a-z]{2,3}(-[A-Za-z0-9]+)*$/.test(code));
if (malformed.length) throw new Error(`locale codes are not BCP 47: ${malformed.join(', ')}`);

// pt-BR is not a valid identifier, so it is exported as ptBR
const identifier = (code) => code.replace(/-(\w)/g, (_, c) => c.toUpperCase());

const base = read('en');
const gaps = [];

// Missing and blank strings fall back to English, so a new upstream key cannot break every locale
const entries = (code) => {
    const values = read(code);
    const missing = Object.keys(base).filter((key) => !values[key]).length;
    if (missing && code !== 'en') gaps.push(`${code} (${missing})`);
    return Object.keys(base)
        .map((key) => `    ${JSON.stringify(key)}: ${JSON.stringify(values[key] || base[key])},`)
        .join('\n');
};

// The MaplibreLocale annotation fails the build if a locale gains or loses a key
const declaration = (code) =>
    `export const ${identifier(code)}: MaplibreLocale = {\n${entries(code)}\n};`;

const member = (code) =>
    code === identifier(code) ? `    ${code},` : `    ${JSON.stringify(code)}: ${identifier(code)},`;

const output = `// Generated by scripts/build-locales.mjs from src/locales/*.json - do not edit.

export const en = {
${entries('en')}
};

export type LocaleKey = keyof typeof en;
export type MaplibreLocale = Record<LocaleKey, string>;

${codes.filter((code) => code !== 'en').map(declaration).join('\n\n')}

export const maplibreLocales = {
${codes.map(member).join('\n')}
} satisfies Record<string, MaplibreLocale>;
`;

writeFileSync(resolve(root, 'src/locales.generated.ts'), output);
console.log(`generated src/locales.generated.ts: ${codes.length} locales`);
if (gaps.length) console.log(`using English for untranslated strings: ${gaps.join(', ')}`);
