export const es = {
  'AttributionControl.ToggleAttribution': 'Alternar atribución',
  'AttributionControl.MapFeedback': 'Comentarios del mapa',
  'FullscreenControl.Enter': 'Entrar en pantalla completa',
  'FullscreenControl.Exit': 'Salir de pantalla completa',
  'GeolocateControl.FindMyLocation': 'Encontrar mi ubicación',
  'GeolocateControl.LocationNotAvailable': 'Ubicación no disponible',
  'LogoControl.Title': 'Logo de MapLibre',
  'Map.Title': 'Mapa',
  'Marker.Title': 'Marcador del mapa',
  'NavigationControl.ResetBearing': 'Restablecer orientación al norte',
  'NavigationControl.ZoomIn': 'Acercar',
  'NavigationControl.ZoomOut': 'Alejar',
  'Popup.Close': 'Cerrar ventana',
  'ScaleControl.Feet': 'pies',
  'ScaleControl.Meters': 'm',
  'ScaleControl.Kilometers': 'km',
  'ScaleControl.Miles': 'mi',
  'ScaleControl.NauticalMiles': 'mn',
  'GlobeControl.Enable': 'Habilitar globo',
  'GlobeControl.Disable': 'Deshabilitar globo',
  'TerrainControl.Enable': 'Habilitar terreno',
  'TerrainControl.Disable': 'Deshabilitar terreno',
  'CooperativeGesturesHandler.WindowsHelpText': 'Use Ctrl + desplazamiento para acercar el mapa',
  'CooperativeGesturesHandler.MacHelpText': 'Use ⌘ + desplazamiento para acercar el mapa',
  'CooperativeGesturesHandler.MobileHelpText': 'Use dos dedos para mover el mapa',
};
