export const fr = {
  'AttributionControl.ToggleAttribution': 'Basculer la source',
  'AttributionControl.MapFeedback': 'Retour sur la carte',
  'FullscreenControl.Enter': 'Passer en plein écran',
  'FullscreenControl.Exit': 'Quitter le plein écran',
  'GeolocateControl.FindMyLocation': 'Trouver ma position',
  'GeolocateControl.LocationNotAvailable': 'Position indisponible',
  'LogoControl.Title': 'Logo MapLibre',
  'Map.Title': 'Carte',
  'Marker.Title': 'Marqueur de carte',
  'NavigationControl.ResetBearing': 'Réinitialiser le cap vers le nord',
  'NavigationControl.ZoomIn': 'Zoom avant',
  'NavigationControl.ZoomOut': 'Zoom arrière',
  'Popup.Close': 'Fermer la popup',
  'ScaleControl.Feet': 'pi',
  'ScaleControl.Meters': 'm',
  'ScaleControl.Kilometers': 'km',
  'ScaleControl.Miles': 'mi',
  'ScaleControl.NauticalMiles': 'nm',
  'GlobeControl.Enable': 'Activer le globe',
  'GlobeControl.Disable': 'Désactiver le globe',
  'TerrainControl.Enable': 'Activer le terrain',
  'TerrainControl.Disable': 'Désactiver le terrain',
  'CooperativeGesturesHandler.WindowsHelpText': 'Utilisez Ctrl + défilement pour zoomer la carte',
  'CooperativeGesturesHandler.MacHelpText': 'Utilisez ⌘ + défilement pour zoomer la carte',
  'CooperativeGesturesHandler.MobileHelpText': 'Utilisez deux doigts pour déplacer la carte',
};
