export const ja = {
  'AttributionControl.ToggleAttribution': '帰属を切り替え',
  'AttributionControl.MapFeedback': '地図のフィードバック',
  'FullscreenControl.Enter': '全画面表示にする',
  'FullscreenControl.Exit': '全画面表示を終了',
  'GeolocateControl.FindMyLocation': '私の位置を見つける',
  'GeolocateControl.LocationNotAvailable': '位置は利用できません',
  'LogoControl.Title': 'MapLibre ロゴ',
  'Map.Title': '地図',
  'Marker.Title': '地図のマーカー',
  'NavigationControl.ResetBearing': '北向きに方位をリセット',
  'NavigationControl.ZoomIn': 'ズームイン',
  'NavigationControl.ZoomOut': 'ズームアウト',
  'Popup.Close': 'ポップアップを閉じる',
  'ScaleControl.Feet': 'ft',
  'ScaleControl.Meters': 'm',
  'ScaleControl.Kilometers': 'km',
  'ScaleControl.Miles': 'mi',
  'ScaleControl.NauticalMiles': 'nm',
  'GlobeControl.Enable': '地球儀を有効にする',
  'GlobeControl.Disable': '地球儀を無効にする',
  'TerrainControl.Enable': '地形を有効にする',
  'TerrainControl.Disable': '地形を無効にする',
  'CooperativeGesturesHandler.WindowsHelpText': 'Ctrl + スクロールで地図をズーム',
  'CooperativeGesturesHandler.MacHelpText': '⌘ + スクロールで地図をズーム',
  'CooperativeGesturesHandler.MobileHelpText': '2本の指で地図を移動させます',
};
