export const ne = {
  'AttributionControl.ToggleAttribution': 'श्रेय टगल गर्नुहोस्',
  'AttributionControl.MapFeedback': 'नक्सा प्रतिकृया',
  'FullscreenControl.Enter': 'पूर्ण पर्दामा प्रवेश गर्नुहोस्',
  'FullscreenControl.Exit': 'पूर्ण पर्दाबाट बाहिर निस्कनुहोस्',
  'GeolocateControl.FindMyLocation': 'मेरो स्थान फेला पार्नुहोस्',
  'GeolocateControl.LocationNotAvailable': 'स्थान उपलब्ध छैन',
  'LogoControl.Title': 'MapLibre लोगो',
  'Map.Title': 'नक्सा',
  'Marker.Title': 'नक्सा मार्कर',
  'NavigationControl.ResetBearing': 'उत्तरतर्फ दिशा पुनः सेट गर्नुहोस्',
  'NavigationControl.ZoomIn': 'जुम बढाउनुहोस्',
  'NavigationControl.ZoomOut': 'जुम घटाउनुहोस्',
  'Popup.Close': 'पपअप बन्द गर्नुहोस्',
  'ScaleControl.Feet': 'फुट',
  'ScaleControl.Meters': 'मिटर',
  'ScaleControl.Kilometers': 'किलोमिटर',
  'ScaleControl.Miles': 'माइल',
  'ScaleControl.NauticalMiles': 'समुद्री माइल',
  'GlobeControl.Enable': 'ग्लोब सक्षम गर्नुहोस्',
  'GlobeControl.Disable': 'ग्लोब अक्षम गर्नुहोस्',
  'TerrainControl.Enable': 'भूभाग सक्षम गर्नुहोस्',
  'TerrainControl.Disable': 'भूभाग अक्षम गर्नुहोस्',
  'CooperativeGesturesHandler.WindowsHelpText': 'नक्सामा जुम गर्न Ctrl + स्क्रोल प्रयोग गर्नुहोस्',
  'CooperativeGesturesHandler.MacHelpText': 'नक्सामा जुम गर्न ⌘ + स्क्रोल प्रयोग गर्नुहोस्',
  'CooperativeGesturesHandler.MobileHelpText': 'नक्सा सार्न दुई औंला प्रयोग गर्नुहोस्',
};
