export const ptBR = {
  'AttributionControl.ToggleAttribution': 'Alternar atribuição',
  'AttributionControl.MapFeedback': 'Feedback do mapa',
  'FullscreenControl.Enter': 'Entrar em tela cheia',
  'FullscreenControl.Exit': 'Sair da tela cheia',
  'GeolocateControl.FindMyLocation': 'Encontrar minha localização',
  'GeolocateControl.LocationNotAvailable': 'Localização não disponível',
  'LogoControl.Title': 'Logotipo MapLibre',
  'Map.Title': 'Mapa',
  'Marker.Title': 'Marcador do mapa',
  'NavigationControl.ResetBearing': 'Redefinir rumo ao norte',
  'NavigationControl.ZoomIn': 'Aproximar',
  'NavigationControl.ZoomOut': 'Afastar',
  'Popup.Close': 'Fechar popup',
  'ScaleControl.Feet': 'pés',
  'ScaleControl.Meters': 'm',
  'ScaleControl.Kilometers': 'km',
  'ScaleControl.Miles': 'mi',
  'ScaleControl.NauticalMiles': 'nm',
  'GlobeControl.Enable': 'Ativar globo',
  'GlobeControl.Disable': 'Desativar globo',
  'TerrainControl.Enable': 'Ativar terreno',
  'TerrainControl.Disable': 'Desativar terreno',
  'CooperativeGesturesHandler.WindowsHelpText': 'Use Ctrl + rolagem para ampliar o mapa',
  'CooperativeGesturesHandler.MacHelpText': 'Use ⌘ + rolagem para ampliar o mapa',
  'CooperativeGesturesHandler.MobileHelpText': 'Use dois dedos para mover o mapa',
};
